<?php
/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

namespace App\Models\Repository;

use Doctrine\ORM\EntityRepository;

class PaymentRepository extends EntityRepository
{

}